# Generated by Django 5.2.5 on 2025-08-28 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectemployee",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_projects",
                to="user.employee",
            ),
        ),
        migrations.AddField(
            model_name="projectemployee",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_employees",
                to="company.project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectemployee",
            unique_together={("project", "employee")},
        ),
    ]
