# Generated by Django 5.2.5 on 2025-08-28 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_projects",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_projects",
                to="company.department",
            ),
        ),
    ]
