# Generated by Django 5.2.5 on 2025-08-29 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_project_company_alter_project_department"),
        ("user", "0004_remove_employee_days_employed_employee_hired_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("review_scheduled", "Review Scheduled"),
                            ("feedback_provided", "Feedback Provided"),
                            ("under_approval", "Under Approval"),
                            ("review_approved", "Review Approved"),
                            ("review_rejected", "Review Rejected"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews_employee",
                        to="user.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Review",
                "verbose_name_plural": "Performance Reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
