# Generated by Django 5.2.5 on 2025-08-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=1, max_length=150, unique=True, verbose_name="Username"
            ),
            preserve_default=False,
        ),
    ]
