# Generated by Django 5.2.5 on 2025-08-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="days_employed",
        ),
        migrations.AddField(
            model_name="employee",
            name="hired_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
